name: Update GitHub Stats Gist
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches: master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: 20

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Github stats box
        run: npx github-stats-box@1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 3c3dabe404ddec8410596ab5f223f552
          ALL_COMMITS: true
          K_FORMAT: false

      - name: Github languages Stats box
        run: npx github-lang-box@1
        env:
          GIST_ID: e6e77169fc620bca4304466d182a3a8d
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USERNAME: cristiandlhoz
          EXCLUDE: ${{ vars.EXCLUDE }}
          EXCLUDE_REPO: ${{ vars.EXCLUDE_REPO }}
          DESCRIPTION: "languages"
